### ISSUE TITLE
There is an index error on your code.

### ISSUE THREAD

**Issue by NatLee** [ewrfcas/QANet_keras#6]
```
CPU EMA assigning weights...
100%|#################################################################################| 347/347 
[21:59<00:00,  3.98s/it]
10546/10546 [==============================] - 138s 13ms/step
Traceback (most recent call last):
  File "train_QANet.py", line 152, in <module>
    callbacks=[qanet_callback])
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 217, in fi
t_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.6/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "train_QANet.py", line 119, in on_epoch_end
    start_logits = logits1[i, :]
IndexError: index 10546 is out of bounds for axis 0 with size 10546
```

Hello!

I used your code to train a model, but I got an error.
When it ran on the end of 2 epochs, it said IndexError.

Thank you.

**Comment by ewrfcas** [comment]
@NatLee I have never met this problem yet. And it is weird that this error happens at the end of 2 epochs. The length of dev_data['qid'] should be the same as each one in dev_data (e.g. the first dim of dev_data['context_id'], dev_data['question_id']...).

**Comment by NatLee** [comment]
我這邊有算出來只有 dev_data['qid'] 長度是10719，其他key的list長度是10534，所以報錯。
改成 `for i, qid in enumerate(dev_data['question_id'])` 讓他大小一樣就行了

不過後面write_predictions又出現另外一個錯
`write_predictions(eval_examples, eval_features, all_results, n_best_size=20, max_answer_length=ans_limit, do_lower_case=False, output_prediction_file=output_prediction_file, output_nbest_file=output_nbest_file)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lee\Desktop\QANet_keras-master\utils\output.py", line 109, in write_predictions
    unique_id_to_result[result.qid] = result
TypeError: unhashable type: 'numpy.ndarray`

result.qid是一個array，卻拿來當成dict的key，於是就噴了 :' (

**Comment by NatLee** [comment]
oh! I got it 
it's my fault : )
thanks!
